### ISSUE TITLE
Camera clips through walls.

### ISSUE THREAD

**Issue by gaeqs** [Slow-Heat-Index/BlockDasher#115]
**Describe the bug**

The camera doesn't avoid blocks.

**To Reproduce**
Go to a level with a wall.
Place the camera inside the wall.

**Expected behavior**
The camera should avoid the blocks or the block should be invisible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 96

**Additional context**
Happens in all versions.

**Comment by damacaa** [comment]
![Captura de pantalla 2021-11-23 153839](https://user-images.githubusercontent.com/49535803/143048903-906b4b51-c0dc-4ae0-ba84-275df062f29c.png)
