### ISSUE TITLE
Information about what does each type of enemy

### ISSUE THREAD

**Issue by pusilanime110** [Slow-Heat-Index/BlockDasher#119]
Please, write the whole report in **english**.

**Describe the solution you'd like**
There should be a guide about what enemies do.

**Describe alternatives you've considered**
Clarify the behaviour of the sphere.

**Comment by gaeqs** [comment]
Please describe your bug using the bug report template and using the English language.

**Comment by darsay** [comment]
The minimalistic nature of game leads players to discover by themselves how enemies work and how they can overcome them.
