### ISSUE TITLE
Change the restart button position.

### ISSUE THREAD

**Issue by YeronMartin** [Slow-Heat-Index/BlockDasher#120]
**Describe the solution you'd like**
Remove the restart button: it stops the fast flow of the game,

<img width="1440" alt="Captura de pantalla 2021-11-23 a las 16 06 47" src="https://user-images.githubusercontent.com/73124295/143050256-415ae81f-d79e-4843-b3a7-0ba33f53981f.png">
<img width="948" alt="Captura de pantalla 2021-11-23 a las 16 06 31" src="https://user-images.githubusercontent.com/73124295/143050268-991ca4e5-1a0f-40e8-9292-d368a03b1270.png">

**Comment by gaeqs** [comment]
Please describe your bug using the bug report template and using the English language.

**Comment by gaeqs** [comment]
The game does not have a fast flow! It's a puzzle game, not an action game! The restart button should stay.
