### ISSUE TITLE
Dash count resets when you enter the pause menu.

### ISSUE THREAD

**Issue by litosart** [Slow-Heat-Index/BlockDasher#121]
**Describe the bug**
When you enter and exte the pause button the dash conter resets to 0.
It fixes itself when you dash again.

**To Reproduce**

1. Start a level.
2. Dash a little.
3. Enter and exit the pause menu.

**Expected behavior**
The dash counter should show the correctr information.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/11397124/143056430-67e59281-08e0-4152-afc5-900aacb20012.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX

**Comment by gaeqs** [comment]
Please describe your bug using the bug report template and using the English language.
