### ISSUE TITLE
More languages available 

### ISSUE THREAD

**Issue by adrianmrt** [Slow-Heat-Index/BlockDasher#122]
**Is your feature request related to a problem? Please describe.**
If you dont know English you can't understand the game.

**Describe the solution you'd like**
It would be nice if the game could be available in other languages 

**Describe alternatives you've considered**
An option for changing the language from inside the game.

**Comment by gaeqs** [comment]
Please describe your bug using the bug report template and using the English language.

**Comment by adrianmrt** [comment]
**Description**
If you dont know English you can't understand the game.

**Alternative**
It would be nice if the game could be available in other languages or an option for changing the language from inside the game.

**Comment by darsay** [comment]
There are few words, and the existing ones, are easy to understand. My 7 years old tried this game and had no problem understanding anything.
