### ISSUE TITLE
Exception for not finding a mobile method on PC

### ISSUE THREAD

**Issue by pusilanime110** [Slow-Heat-Index/BlockDasher#123]
**Describe the bug**

On PC, the browser tries to execute a only-mobile method.

**Impact**
Medium impact.

**To Reproduce**
1. Open the game on PC.
2. Open the browser's console.
3. Search the error.

**Screenshots**
![bug2](https://user-images.githubusercontent.com/56488179/143051564-635e4211-c6d5-4305-b11c-627be56f3fb4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96

**Additional context**

**Comment by gaeqs** [comment]
I'm not able to reproduce the exception in Firefox or Chrome. Do you have to do something in the game?

**Comment by pusilanime110** [comment]
It happens when you are on full screen

**Comment by gaeqs** [comment]
I was able to reproduce the error, but it's from a itch.io script. We don't have control over this.
