### ISSUE TITLE
Buttons when playing on mobile phone

### ISSUE THREAD

**Issue by adrianmrt** [Slow-Heat-Index/BlockDasher#125]
**Is your feature request related to a problem? Please describe.**
You can get tired when playing on the phone by always dragging the finger on the screen. 
Besides, camera rotation buttons are a little bit too big.

**Describe the solution you'd like**
Consider making the buttons smaller or changing the way on input.

**Describe alternatives you've considered**
Maybe adding a virtual joystick could help.

**Comment by gaeqs** [comment]
> You can get tired when playing on the phone by always dragging the finger on the screen.

That's the gimmick of the game: to **dash** your finger to move.
The buttons are too big indeed.
