### ISSUE TITLE
Zoom option

### ISSUE THREAD

**Issue by adrianmrt** [Slow-Heat-Index/BlockDasher#131]
**Is your feature request related to a problem? Please describe.**
Sometimes when playing on the phone the experience would improve if you could zoom into the game and see better the environment.

**Describe the solution you'd like**
A zoom option.

**Describe alternatives you've considered**
Zooming with the fingers would be easy an practical.

**Comment by gaeqs** [comment]
Maybe a option to change the field of view of the camera would be a good idea!

**Comment by darsay** [comment]
Zooming could lead to missinputs
