### ISSUE TITLE
Sometimes camera rotation resets when rotating fast

### ISSUE THREAD

**Issue by pusilanime110** [Slow-Heat-Index/BlockDasher#132]
**Describe the bug**
When you rotate quickly the camera, sometimes it will reset and stop the animation

**Impact**
Medium Impact

**To Reproduce**
1. Quickly rotate the camera with E or Q

**Expected behavior**
The animation shouldn't stop

**Screenshots**
https://user-images.githubusercontent.com/56488179/143054729-5afe1f90-cf70-4128-9f34-5c332161bdfa.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96

**Comment by gaeqs** [comment]
We'll disable the button input for half a second to avoid this behaviour.
