### ISSUE TITLE
Bubbles when restart game

### ISSUE THREAD

**Issue by YeronMartin** [Slow-Heat-Index/BlockDasher#136]
Please, write the whole report in **english**.

**Describe the bug**
The bubbles icon is still being rendered when you restart the game.

**To Reproduce**
1. Swim.
2. Die due to a shark attack or fro falling into the void
3. Restart the game

**Expected behavior**
The bubbles shouldn't be render when the game start again.

**Screenshots**
<img width="783" alt="Captura de pantalla 2021-11-25 a las 14 50 42" src="https://user-images.githubusercontent.com/73124295/143455040-9be13009-0955-4e7a-ad3b-bb58290ed849.png">

**Desktop (please complete the following information):**
 - OS: IOS Big Sur
 - Browser Chrome

**Comment by gaeqs** [comment]
I think it's the same issue as #124 but with the bubble sprite.
